### ISSUE TITLE
Media_player widget: Prev/Next buttons missing

### ISSUE THREAD

**Issue by vrs01** [JulianKahnert/hygge#1]
Hi!

Nice skin, dude!

But in the media_player widget I don't see the prev/next buttons. Can those be added?

Best, vrs01

![media_player](https://user-images.githubusercontent.com/9992988/27693525-f46c430e-5ce9-11e7-906b-b5ae8e96fe68.PNG)

**Comment by JulianKahnert** [comment]
Hey, cool that you use the theme! 🙂 this is very strange because it works here ...
![bildschirmfoto 2017-07-02 um 23 07 40](https://user-images.githubusercontent.com/6580313/27773503-6eb1e284-5f7b-11e7-868d-309509cab988.png)

Which version of HADashboard are you running and can you find the buttons on the default theme? 🤔

**Comment by vrs01** [comment]
I use the most recent github commit. And it works in the default theme. I have a mpd and a spotify player integrated. They show previous / play / next buttons in one row. Not stop / pause / play as in your apple tv snapshot.  In the hygge theme, the clickable area of the pause button is as wide as the whole widget. Have you tried a different media_player than the apple tv with the hygge theme?

**Comment by JulianKahnert** [comment]
Ah, it seems to be a problem with the new version of HADashboard. I try to have a look at it in the next few days ...

**Comment by JulianKahnert** [comment]
I think 2d1ba76396d7f422d58481c1ce23880ae40e11ec should fix the problem. 🙂

**Comment by vrs01** [comment]
Yes, that works! Thanks!
